### ISSUE TITLE
AttributeError: 'FeatureSplattingModel' object has no attribute 'info'

### ISSUE THREAD

**Issue by jpeng2012** [vuer-ai/feature-splatting#5]
Got his error when run 
ns-train feature-splatting --data data/nerfstudio/poster

Traceback (most recent call last):
  File "/miniforge3/envs/feature_splatting_ns/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File /nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/nerfstudio/nerfstudio/engine/trainer.py", line 270, in train
    callback.run_callback_at_location(
  File "/nerfstudio/nerfstudio/engine/callbacks.py", line 116, in run_callback_at_location
    self.run_callback(step=step)
  File "/nerfstudio/nerfstudio/engine/callbacks.py", line 106, in run_callback
    self.func(*self.args, **self.kwargs, step=step)
  File "/nerfstudio/nerfstudio/models/splatfacto.py", line 429, in step_post_backward
    info=self.info,
  File "/miniforge3/envs/feature_splatting_ns/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'FeatureSplattingModel' object has no attribute 'info'

**Comment by jpeng2012** [comment]
It can be fixed by replace  "info" to "self.info" in model.py
